# Generated by Django 3.2.5 on 2021-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/profile/images/default.jpg', null=True, upload_to='media/profile/images'),
        ),
    ]
