# Generated by Django 3.2.5 on 2021-08-19 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
